name: Check Deployment
on:
  workflow_call:
    inputs:
      passci:
        description: 'Pass CI'
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      passci:
        description: 'Pass CI'
        required: true
        type: boolean
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  check-branches:
    if:
      startsWith(github.head_ref, 'renovate/') || contains(github.head_ref,
      'no-deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Pass CI with input
        if: ${{ inputs.passci }}
        run: exit 0
      - name: Pass CI with label
        if: contains(github.event.pull_request.labels.*.name, 'deploy')
        run: exit 0
      - name: Fail
        run: exit 1
