name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Version to publish'
        required: true
        options: ['patch', 'minor', 'major', 'pre']
        default: 'patch'
      dry-run:
        type: boolean
        description: 'Dry run'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dvcorg'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - run: |
          yarn release:ci ${{ github.event.inputs.version }} --dry-run=${{ github.event.inputs.dry-run }}
          if [ "${{ github.event.inputs.dry-run }}" = "false" ]; then
            cd ./packages/gatsby-theme-iterative
            yarn publish
          fi

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
